<?php
/**
 * MediaSourceAllOfTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Cloudinary\MediaDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Media Delivery
 *
 * Media Delivery API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Cloudinary\MediaDelivery\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MediaSourceAllOfTest Class Doc Comment
 *
 * @category    Class
 * @description MediaSourceAllOf
 * @package     Cloudinary\MediaDelivery
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MediaSourceAllOfTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MediaSourceAllOf"
     */
    public function testMediaSourceAllOf()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
