<?php
/**
 * MediaTargetApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Cloudinary\MediaDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Media Delivery
 *
 * Media Delivery API
 *
 * The version of the OpenAPI document: 0.1.0-beta
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Cloudinary\MediaDelivery\Test\Api;

use \Cloudinary\MediaDelivery\Configuration;
use \Cloudinary\MediaDelivery\ApiException;
use \Cloudinary\MediaDelivery\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MediaTargetApiTest Class Doc Comment
 *
 * @category Class
 * @package  Cloudinary\MediaDelivery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MediaTargetApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createMediaTarget
     *
     * Create a new Media Target.
     *
     */
    public function testCreateMediaTarget()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteMediaTarget
     *
     * Delete the Media Target.
     *
     */
    public function testDeleteMediaTarget()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMediaTarget
     *
     * Get the Media Target.
     *
     */
    public function testGetMediaTarget()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMediaTargets
     *
     * Get the Media Targets.
     *
     */
    public function testGetMediaTargets()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateMediaTarget
     *
     * Update the Media Target.
     *
     */
    public function testUpdateMediaTarget()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
